/**
 * GPU Particle Swarm — tens of thousands of particles orbiting moving
 * attractors. Particle position+velocity live in float textures, updated by a
 * fullscreen sim pass, then drawn as additive points (the point's vertex
 * shader fetches its position from the state texture by gl_VertexID).
 */
import { createGLRuntime, createFullscreenPass, createPingPong, buildProgram } from './gl-base.js'

const PARTICLES_SIDE = 256 // 256x256 = 65,536 particles

const SIM_FRAG = `#version 300 es
precision highp float;
uniform sampler2D uState;   // xy=pos (clip space-ish), zw=vel
uniform vec2 uTexel;
uniform float uTime;
uniform float uDt;
out vec4 outState;

void main() {
  vec2 uv = gl_FragCoord.xy * uTexel;
  vec4 s = texture(uState, uv);
  vec2 pos = s.xy;
  vec2 vel = s.zw;

  // Two orbiting attractors.
  vec2 a1 = 0.6 * vec2(cos(uTime * 0.5), sin(uTime * 0.4));
  vec2 a2 = 0.6 * vec2(cos(uTime * 0.3 + 2.0), sin(uTime * 0.6 + 1.0));

  vec2 d1 = a1 - pos; vec2 d2 = a2 - pos;
  float r1 = max(dot(d1, d1), 0.01);
  float r2 = max(dot(d2, d2), 0.01);
  vec2 acc = d1 / r1 * 0.02 + d2 / r2 * 0.02;
  // Tangential swirl for orbiting motion.
  acc += vec2(-d1.y, d1.x) / r1 * 0.01;

  vel += acc * uDt * 60.0;
  vel *= 0.985; // damping
  pos += vel * uDt;

  // Wrap around the [-1,1] box.
  pos = mod(pos + 1.0, 2.0) - 1.0;

  outState = vec4(pos, vel);
}`

const DRAW_VERT = `#version 300 es
precision highp float;
uniform sampler2D uState;
uniform float uSide;
out float vSpeed;
void main() {
  int id = gl_VertexID;
  int x = id % int(uSide);
  int y = id / int(uSide);
  vec2 uv = (vec2(float(x), float(y)) + 0.5) / uSide;
  vec4 s = texture(uState, uv);
  vSpeed = length(s.zw);
  gl_Position = vec4(s.xy, 0.0, 1.0);
  gl_PointSize = 1.5;
}`

const DRAW_FRAG = `#version 300 es
precision highp float;
in float vSpeed;
out vec4 outColor;
void main() {
  vec3 col = 0.5 + 0.5 * cos(6.2831 * (vSpeed * 2.0 + vec3(0.0, 0.33, 0.67)));
  // Multiply blend over a white background ("ink on paper"): emit a value
  // close to 1.0 so a single particle barely tints the paper and overlaps
  // build up saturated color. mix toward white keeps it light and airy.
  vec3 ink = mix(vec3(1.0), col, 0.5);
  outColor = vec4(ink, 1.0);
}`

export default {
  name: 'Particle Swarm',
  create(canvas) {
    let runtime = null, gl = null
    let sim = null, drawProg = null, pp = null, vao = null
    let last = 0
    const SIDE = PARTICLES_SIDE
    const COUNT = SIDE * SIDE

    function seed() {
      const data = new Float32Array(COUNT * 4)
      for (let i = 0; i < COUNT; i++) {
        data[i * 4 + 0] = Math.random() * 2 - 1
        data[i * 4 + 1] = Math.random() * 2 - 1
        data[i * 4 + 2] = (Math.random() * 2 - 1) * 0.1
        data[i * 4 + 3] = (Math.random() * 2 - 1) * 0.1
      }
      return data
    }

    return {
      start() {
        runtime = createGLRuntime(canvas)
        gl = runtime.gl
        gl.getExtension('EXT_color_buffer_float')
        pp = createPingPong(gl, SIDE, SIDE, seed())
        sim = createFullscreenPass(gl, SIM_FRAG)

        // Point-draw program: empty VAO, vertices generated by gl_VertexID,
        // each fetching its particle's position from the state texture.
        drawProg = buildProgram(gl, DRAW_VERT, DRAW_FRAG)
        vao = gl.createVertexArray()

        last = 0
        gl.enable(gl.BLEND)
        gl.blendFunc(gl.DST_COLOR, gl.ZERO) // multiply (ink on white paper)

        runtime.start((time) => {
          const dt = Math.min(time - last, 0.05) || 0.016
          last = time

          // Sim pass.
          gl.disable(gl.BLEND)
          gl.bindFramebuffer(gl.FRAMEBUFFER, pp.write.fbo)
          gl.viewport(0, 0, SIDE, SIDE)
          sim.draw((g, p) => {
            g.activeTexture(g.TEXTURE0)
            g.bindTexture(g.TEXTURE_2D, pp.read.tex)
            g.uniform1i(g.getUniformLocation(p, 'uState'), 0)
            g.uniform2f(g.getUniformLocation(p, 'uTexel'), 1 / SIDE, 1 / SIDE)
            g.uniform1f(g.getUniformLocation(p, 'uTime'), time)
            g.uniform1f(g.getUniformLocation(p, 'uDt'), dt)
          })
          pp.swap()

          // Draw pass: white paper, multiply-blend colored "ink" particles.
          gl.bindFramebuffer(gl.FRAMEBUFFER, null)
          gl.viewport(0, 0, canvas.width, canvas.height)
          gl.enable(gl.BLEND)
          gl.blendFunc(gl.DST_COLOR, gl.ZERO)
          gl.clearColor(1, 1, 1, 1)
          gl.clear(gl.COLOR_BUFFER_BIT)
          gl.useProgram(drawProg.program)
          gl.bindVertexArray(vao)
          gl.activeTexture(gl.TEXTURE0)
          gl.bindTexture(gl.TEXTURE_2D, pp.read.tex)
          gl.uniform1i(gl.getUniformLocation(drawProg.program, 'uState'), 0)
          gl.uniform1f(gl.getUniformLocation(drawProg.program, 'uSide'), SIDE)
          gl.drawArrays(gl.POINTS, 0, COUNT)
        })
      },
      stop() {
        if (sim) { sim.destroy(); sim = null }
        if (drawProg) { drawProg.destroy(); drawProg = null }
        if (vao) { gl.deleteVertexArray(vao); vao = null }
        if (pp) { pp.destroy(); pp = null }
        if (runtime) { runtime.destroy(); runtime = null }
        gl = null
      }
    }
  }
}
